source 'https://github.com/CocoaPods/Specs.git'

target 'TFFormDescriptor', :exclusive => true do
    #pod 'TFTableDescriptor', :path => "../../TFTableDescriptor"
  pod "TFFormDescriptor", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TFFormDescriptor", :path => "../"

  pod 'Kiwi'
end
